{{- if or .Values.config.apiKey .Values.config.scimKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "furnace.fullname" . }}
  labels:
    {{- include "furnace.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.apiKey }}
  FURNACE_API_KEY: {{ .Values.config.apiKey | quote }}
  {{- end }}
  {{- if .Values.config.scimKey }}
  FURNACE_SCIM_KEY: {{ .Values.config.scimKey | quote }}
  {{- end }}
{{- end }}
