{{- if or .Values.config.apiKey .Values.config.scimKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authpilot.fullname" . }}
  labels:
    {{- include "authpilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.apiKey }}
  AUTHPILOT_API_KEY: {{ .Values.config.apiKey | quote }}
  {{- end }}
  {{- if .Values.config.scimKey }}
  AUTHPILOT_SCIM_KEY: {{ .Values.config.scimKey | quote }}
  {{- end }}
{{- end }}
