apiVersion: v1
kind: Service
metadata:
  name: {{ include "authpilot.fullname" . }}
  labels:
    {{- include "authpilot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "authpilot.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: protocol
      port: {{ .Values.service.protocolPort }}
      targetPort: protocol
      protocol: TCP
